# -*- coding: utf-8 -*-
"""web_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pqe39XJTmnd5HDng6qLcaRYV27NS1ZwB
"""

# !pip install flask

import pickle
from flask import Flask, request, render_template

# Load the pickled vectorizer and model.
pickled_vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))
pickled_model = pickle.load(open('model.pkl', 'rb'))

# Create a Flask application.
app = Flask(__name__)

# Define the index route.
@app.route("/", methods=["GET", "POST"])
def index():
    result = ""
    if request.method == "POST":
        # Get user input from the form.
        user_input = request.form["user_input"]

        # Vectorize the user input using the loaded vectorizer.
        user_input = pickled_vectorizer.transform([user_input])  # Pass user input as a list

        # Predict using the loaded model.
        sentiment = pickled_model.predict(user_input)
        if sentiment[0] == -1:
          result = 'Negative'
        elif sentiment[0] == 0:
          result = 'Neutral'
        else:
          result = 'Positive'

    # Render the HTML template with the result.
    return render_template("index.html", result=result)

# Run the Flask application if this script is the main module.
if __name__ == "__main__":
    app.run(debug=True)